// ---------------------------------------------------------------------
// This agent file is auto-generated by behaviac designer, but you should
// implement the methods of the agent class if necessary!
// ---------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

[behaviac.TypeMetaInfo("FSM_Ctrl", "FSM_Ctrl")]
public class FSM_Ctrl : behaviac.Agent
{
	// properties

	[behaviac.MemberMetaInfo("Status", "Status")]
	public int Status = 0;

	[behaviac.MemberMetaInfo("MouseStatus", "MouseStatus")]
	public int MouseStatus = 0;

	[behaviac.MemberMetaInfo("isConAva", "isConAva")]
	public bool isConAva = false;

	// methods

	[behaviac.MethodMetaInfo("ReadyConstruct", "ReadyConstruct")]
	private void ReadyConstruct()
	{
		Debug.Log("请选择建筑位置");
		// Write your logic codes here.
	}

	[behaviac.MethodMetaInfo("Selecting", "Selecting")]
	private void Selecting()
	{
		Debug.Log ("请选择单位");
		// Write your logic codes here.
	}

	[behaviac.MethodMetaInfo("Constructing", "Constructing")]
	private void Constructing()
	{
		Debug.Log ("哦哦哦");
		// Write your logic codes here.
	}

}
