// ---------------------------------------------------------------------
// This agent file is auto-generated by behaviac designer, but you should
// implement the methods of the agent class if necessary!
// ---------------------------------------------------------------------

using System.Collections.Generic;

[behaviac.TypeMetaInfo("Unit", "单位超类")]
public class Unit : behaviac.Agent
{
	// methods

	[behaviac.MethodMetaInfo("SearchEnemy", "SearchEnemy")]
	private bool SearchEnemy()
	{
		// Write your logic codes here.

		return false;
	}

	[behaviac.MethodMetaInfo("Attack", "Attack")]
	private void Attack()
	{
		// Write your logic codes here.
	}

	[behaviac.MethodMetaInfo("GoToDes", "GoToDes")]
	private void GoToDes()
	{
		// Write your logic codes here.
	}

}
